spring.application.name=medical-appointment

server.port=8082

server.servlet.context-path=/medical-appointment

# Databases #
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.open-in-view=false

springdoc.swagger-ui.path= /swagger-ui.html
springdoc.api-docs.path= /api-docs
springdoc.version= 2.3.0

quartz.jobCron=0/30 * * * * ?
quartz.jobGroup=mail-quartz-group
quartz.loadDataGroup=Load-data-quartz-group

## MailProperties
spring.mail.host=galaxy.edu.pe
spring.mail.port=587
spring.mail.username=demo@galaxy.edu.pe
spring.mail.password=MsY1E,a4E-VL
#spring.mail.password=${MAIL_PASSWORD:MsY1E,a4E-VL}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ws.externo.entidad.user.username=ADMIN
ws.externo.entidad.user.password=123