spring.application.name=medical-appointment

server.port=8082

server.servlet.context-path=/medical-appointment

# Databases #
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.open-in-view=false